//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Management.DML.MainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyDetailsLookup
    {
        public int ID { get; set; }
        public int CompetencyLookupID { get; set; }
        public string CompetencyThemesEn { get; set; }
        public string CompetencyThemesAr { get; set; }
        public string BehavioralDescriptionEn { get; set; }
        public string BehavioralDescriptionAr { get; set; }
    
        public virtual CompetencyLookup CompetencyLookup { get; set; }
    }
}
