//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Management.DML.MainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyLookup
    {
        public CompetencyLookup()
        {
            this.CompetencyDetailsLookups = new HashSet<CompetencyDetailsLookup>();
            this.Goals = new HashSet<Goal>();
        }
    
        public int ID { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
    
        public virtual ICollection<CompetencyDetailsLookup> CompetencyDetailsLookups { get; set; }
        public virtual ICollection<Goal> Goals { get; set; }
    }
}
