//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicRelation.DML.MainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_SubPrivilege
    {
        public Form_SubPrivilege()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MainPrivilegeID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Form_MainPrivilege Form_MainPrivilege { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
