//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Management.DML.MainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string MeasurementStandard { get; set; }
        public int RelativeWeight { get; set; }
        public string TargetOutput { get; set; }
        public int Fulfillment { get; set; }
        public string Type { get; set; }
        public Nullable<int> CompetencyLookupID { get; set; }
    
        public virtual CompetencyLookup CompetencyLookup { get; set; }
        public virtual Request Request { get; set; }
    }
}
