//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Management.DML.MainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRSAllowedUser
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string PositionName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public string DelegateToUserName { get; set; }
        public Nullable<System.DateTime> DelegateStartDate { get; set; }
        public Nullable<System.DateTime> DelegateEndDate { get; set; }
    }
}
