//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Management.DML.MainEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompetencyDetailsLookup> CompetencyDetailsLookups { get; set; }
        public virtual DbSet<CompetencyLookup> CompetencyLookups { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<HRSAllowedUser> HRSAllowedUsers { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<RequestType> RequestTypes { get; set; }
        public virtual DbSet<SAction> SActions { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SupervisorUser> SupervisorUsers { get; set; }
    }
}
