//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Management.DML.MainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Goals = new HashSet<Goal>();
            this.Request1 = new HashSet<Request>();
        }
    
        public int ID { get; set; }
        public int StatusID { get; set; }
        public int RequestTypeID { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public int Year { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Note { get; set; }
        public string Attachment { get; set; }
        public string RequesterUserName { get; set; }
        public string RequesterUserEnglishName { get; set; }
        public string RequesterUserEmail { get; set; }
        public string RequesterPositionCode { get; set; }
        public string RequesterPositionName { get; set; }
        public string RequesterDeptCode { get; set; }
        public string RequesterDeptEnglishName { get; set; }
        public Nullable<bool> DeptHead_Approval { get; set; }
        public string DeptHead_UserName { get; set; }
        public string DeptHead_Email { get; set; }
        public string DeptHead_EnglishName { get; set; }
        public Nullable<bool> DeptHead_Recieved { get; set; }
        public Nullable<System.DateTime> DeptHead_RecievedDateTime { get; set; }
        public Nullable<bool> DeptHead_Seen { get; set; }
        public Nullable<System.DateTime> DeptHead_SeenDateTime { get; set; }
        public Nullable<System.DateTime> DeptHead_ApprovalDateTime { get; set; }
        public string DeptHead_Reason { get; set; }
        public string Employee_Grade { get; set; }
        public string Employee_EnglishName { get; set; }
        public string Employee_DepartmentEnglishName { get; set; }
        public string Employee_Position { get; set; }
        public string Employee_Email { get; set; }
        public string Employee_UserName { get; set; }
        public Nullable<bool> Employee_Recieved { get; set; }
        public Nullable<System.DateTime> Employee_RecievedDateTime { get; set; }
        public Nullable<bool> Employee_Seen { get; set; }
        public Nullable<System.DateTime> Employee_SeenDateTime { get; set; }
        public Nullable<bool> Employee_Approval { get; set; }
        public Nullable<System.DateTime> Employee_ApprovalDateTime { get; set; }
        public string Employee_Reason { get; set; }
        public string Employee_Comment { get; set; }
        public Nullable<int> Employee_ActionID { get; set; }
        public Nullable<System.DateTime> Employee_ActionDateTime { get; set; }
        public Nullable<int> Employee_ReasonID { get; set; }
        public bool IsFinished { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public bool IsDeleted { get; set; }
        public string DeleteUserName { get; set; }
        public string DeleteFullName { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<bool> FeedBackGiven { get; set; }
        public Nullable<System.DateTime> FeedBackGivenDateTime { get; set; }
        public Nullable<double> AchievementFeedBack { get; set; }
        public Nullable<double> TimeFeedBack { get; set; }
        public Nullable<double> SatisfacationFeedBack { get; set; }
        public string DirectManager_EnglishName { get; set; }
        public string DirectManager_Position { get; set; }
        public string DirectManager_Email { get; set; }
        public string DirectManager_UserName { get; set; }
        public Nullable<bool> DirectManager_Recieved { get; set; }
        public Nullable<System.DateTime> DirectManager_RecievedDateTime { get; set; }
        public Nullable<bool> DirectManager_Seen { get; set; }
        public Nullable<System.DateTime> DirectManager_SeenDateTime { get; set; }
        public Nullable<bool> DirectManager_Approval { get; set; }
        public Nullable<System.DateTime> DirectManager_ApprovalDateTime { get; set; }
        public string DirectManager_Reason { get; set; }
        public string DirectManager_Comment { get; set; }
        public Nullable<int> DirectManager_ActionID { get; set; }
        public Nullable<System.DateTime> DirectManager_ActionDateTime { get; set; }
        public Nullable<int> DirectManager_ReasonID { get; set; }
        public int RequestCounter { get; set; }
        public Nullable<int> RefrenceID { get; set; }
        public string HR_PerformanceUnit_EnglishName { get; set; }
        public string HR_PerformanceUnit_DepartmentEnglishName { get; set; }
        public string HR_PerformanceUnit_Position { get; set; }
        public string HR_PerformanceUnit_Email { get; set; }
        public string HR_PerformanceUnit_UserName { get; set; }
        public Nullable<bool> HR_PerformanceUnit_Recieved { get; set; }
        public Nullable<System.DateTime> HR_PerformanceUnit_RecievedDateTime { get; set; }
        public Nullable<bool> HR_PerformanceUnit_Seen { get; set; }
        public Nullable<System.DateTime> HR_PerformanceUnit_SeenDateTime { get; set; }
        public Nullable<bool> HR_PerformanceUnit_Approval { get; set; }
        public Nullable<System.DateTime> HR_PerformanceUnit_ApprovalDateTime { get; set; }
        public string HR_PerformanceUnit_Reason { get; set; }
        public string HR_PerformanceUnit_Comment { get; set; }
        public Nullable<int> HR_PerformanceUnit_ActionID { get; set; }
        public Nullable<System.DateTime> HR_PerformanceUnit_ActionDateTime { get; set; }
        public Nullable<int> HR_PerformanceUnit_ReasonID { get; set; }
        public string HR_ManagerOfPersonal_EnglishName { get; set; }
        public string HR_ManagerOfPersonal_DepartmentEnglishName { get; set; }
        public string HR_ManagerOfPersonal_Position { get; set; }
        public string HR_ManagerOfPersonal_Email { get; set; }
        public string HR_ManagerOfPersonal_UserName { get; set; }
        public Nullable<bool> HR_ManagerOfPersonal_Recieved { get; set; }
        public Nullable<System.DateTime> HR_ManagerOfPersonal_RecievedDateTime { get; set; }
        public Nullable<bool> HR_ManagerOfPersonal_Seen { get; set; }
        public Nullable<System.DateTime> HR_ManagerOfPersonal_SeenDateTime { get; set; }
        public Nullable<bool> HR_ManagerOfPersonal_Approval { get; set; }
        public Nullable<System.DateTime> HR_ManagerOfPersonal_ApprovalDateTime { get; set; }
        public string HR_ManagerOfPersonal_Reason { get; set; }
        public string HR_ManagerOfPersonal_Comment { get; set; }
        public Nullable<int> HR_ManagerOfPersonal_ActionID { get; set; }
        public Nullable<System.DateTime> HR_ManagerOfPersonal_ActionDateTime { get; set; }
        public Nullable<int> HR_ManagerOfPersonal_ReasonID { get; set; }
        public string HR_Director_EnglishName { get; set; }
        public string HR_Director_DepartmentEnglishName { get; set; }
        public string HR_Director_Position { get; set; }
        public string HR_Director_Email { get; set; }
        public string HR_Director_UserName { get; set; }
        public Nullable<bool> HR_Director_Recieved { get; set; }
        public Nullable<System.DateTime> HR_Director_RecievedDateTime { get; set; }
        public Nullable<bool> HR_Director_Seen { get; set; }
        public Nullable<System.DateTime> HR_Director_SeenDateTime { get; set; }
        public Nullable<bool> HR_Director_Approval { get; set; }
        public Nullable<System.DateTime> HR_Director_ApprovalDateTime { get; set; }
        public string HR_Director_Reason { get; set; }
        public string HR_Director_Comment { get; set; }
        public Nullable<int> HR_Director_ActionID { get; set; }
        public Nullable<System.DateTime> HR_Director_ActionDateTime { get; set; }
        public Nullable<int> HR_Director_ReasonID { get; set; }
        public string RejectedBy { get; set; }
        public string PendingToUserName { get; set; }
        public bool IsRejectedByEmpFirstTime { get; set; }
        public bool IsRejectedByEmpSecondTime { get; set; }
        public string Employee_DeptCode { get; set; }
        public string Employee_StaffID { get; set; }
    
        public virtual ICollection<Goal> Goals { get; set; }
        public virtual Reason FK_Request_DirectManager_Reason { get; set; }
        public virtual Reason FK_Request_Employee_Reason { get; set; }
        public virtual Reason FK_Request_HR_Director_ReasonID { get; set; }
        public virtual Reason FK_Request_HR_ManagerOfPersonal_ReasonID { get; set; }
        public virtual Reason FK_Request_HR_PerformanceUnit_ReasonID { get; set; }
        public virtual SAction FK_Request_DirectManager_SAction { get; set; }
        public virtual SAction FK_Request_Employee_SAction { get; set; }
        public virtual SAction FK_Request_HR_Director_ActionID { get; set; }
        public virtual SAction FK_Request_HR_ManagerOfPersonal_ActionID { get; set; }
        public virtual SAction FK_Request_HR_PerformanceUnit_ActionID { get; set; }
        public virtual ICollection<Request> Request1 { get; set; }
        public virtual Request Request2 { get; set; }
        public virtual RequestType RequestType { get; set; }
        public virtual Status Status { get; set; }
    }
}
