//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Management.DML.MainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorUser
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public string EmployeeFullNameEnglish { get; set; }
        public string TradeCategory { get; set; }
        public string TradeGrade { get; set; }
        public string TradeDescriptionEnglish { get; set; }
        public string DepartmentNameEnglish { get; set; }
        public string ContractTypeDescription { get; set; }
        public bool IsSupervisor { get; set; }
    }
}
