//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Management.BLL.HRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HRService.IHR")]
    public interface IHR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeInfo", ReplyAction="http://tempuri.org/IHR/GetEmployeeInfoResponse")]
        System.Data.DataSet GetEmployeeInfo(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeInfo", ReplyAction="http://tempuri.org/IHR/GetEmployeeInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeInfoAsync(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllEmployees", ReplyAction="http://tempuri.org/IHR/GetAllEmployeesResponse")]
        System.Data.DataSet GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllEmployees", ReplyAction="http://tempuri.org/IHR/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllEmployeesDept", ReplyAction="http://tempuri.org/IHR/GetAllEmployeesDeptResponse")]
        System.Data.DataSet GetAllEmployeesDept(string deptcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllEmployeesDept", ReplyAction="http://tempuri.org/IHR/GetAllEmployeesDeptResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllEmployeesDeptAsync(string deptcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetDept", ReplyAction="http://tempuri.org/IHR/GetDeptResponse")]
        System.Data.DataSet GetDept(string deptname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetDept", ReplyAction="http://tempuri.org/IHR/GetDeptResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDeptAsync(string deptname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllAuthorities", ReplyAction="http://tempuri.org/IHR/GetAllAuthoritiesResponse")]
        System.Data.DataSet GetAllAuthorities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllAuthorities", ReplyAction="http://tempuri.org/IHR/GetAllAuthoritiesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllAuthoritiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllCompany", ReplyAction="http://tempuri.org/IHR/GetAllCompanyResponse")]
        System.Data.DataSet GetAllCompany(string compcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllCompany", ReplyAction="http://tempuri.org/IHR/GetAllCompanyResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllCompanyAsync(string compcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllCities", ReplyAction="http://tempuri.org/IHR/GetAllCitiesResponse")]
        System.Data.DataSet GetAllCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllCities", ReplyAction="http://tempuri.org/IHR/GetAllCitiesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllCitiescode", ReplyAction="http://tempuri.org/IHR/GetAllCitiescodeResponse")]
        System.Data.DataSet GetAllCitiescode(string citycode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetAllCitiescode", ReplyAction="http://tempuri.org/IHR/GetAllCitiescodeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllCitiescodeAsync(string citycode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Getallporter", ReplyAction="http://tempuri.org/IHR/GetallporterResponse")]
        System.Data.DataSet Getallporter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Getallporter", ReplyAction="http://tempuri.org/IHR/GetallporterResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetallporterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Getallporterdept", ReplyAction="http://tempuri.org/IHR/GetallporterdeptResponse")]
        System.Data.DataSet Getallporterdept(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Getallporterdept", ReplyAction="http://tempuri.org/IHR/GetallporterdeptResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetallporterdeptAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Getallporterempno", ReplyAction="http://tempuri.org/IHR/GetallporterempnoResponse")]
        System.Data.DataSet Getallporterempno(string pemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Getallporterempno", ReplyAction="http://tempuri.org/IHR/GetallporterempnoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetallporterempnoAsync(string pemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Getsalaryemp", ReplyAction="http://tempuri.org/IHR/GetsalaryempResponse")]
        System.Data.DataSet Getsalaryemp(string semp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Getsalaryemp", ReplyAction="http://tempuri.org/IHR/GetsalaryempResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetsalaryempAsync(string semp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeVactionDays", ReplyAction="http://tempuri.org/IHR/GetEmployeeVactionDaysResponse")]
        int GetEmployeeVactionDays(string _date, string _staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeVactionDays", ReplyAction="http://tempuri.org/IHR/GetEmployeeVactionDaysResponse")]
        System.Threading.Tasks.Task<int> GetEmployeeVactionDaysAsync(string _date, string _staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeGrade", ReplyAction="http://tempuri.org/IHR/GetEmployeeGradeResponse")]
        string GetEmployeeGrade(string _staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeGrade", ReplyAction="http://tempuri.org/IHR/GetEmployeeGradeResponse")]
        System.Threading.Tasks.Task<string> GetEmployeeGradeAsync(string _staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertificateEmp", ReplyAction="http://tempuri.org/IHR/GetCertificateEmpResponse")]
        int GetCertificateEmp(string _staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertificateEmp", ReplyAction="http://tempuri.org/IHR/GetCertificateEmpResponse")]
        System.Threading.Tasks.Task<int> GetCertificateEmpAsync(string _staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetSalaryFor", ReplyAction="http://tempuri.org/IHR/GetSalaryForResponse")]
        System.Data.DataSet GetSalaryFor(string mthyr, string empnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetSalaryFor", ReplyAction="http://tempuri.org/IHR/GetSalaryForResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSalaryForAsync(string mthyr, string empnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetSeqNo", ReplyAction="http://tempuri.org/IHR/GetSeqNoResponse")]
        string GetSeqNo(string mthyr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetSeqNo", ReplyAction="http://tempuri.org/IHR/GetSeqNoResponse")]
        System.Threading.Tasks.Task<string> GetSeqNoAsync(string mthyr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpLastVaction", ReplyAction="http://tempuri.org/IHR/GetEmpLastVactionResponse")]
        System.Data.DataSet GetEmpLastVaction(string empnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpLastVaction", ReplyAction="http://tempuri.org/IHR/GetEmpLastVactionResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpLastVactionAsync(string empnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpContractInfo", ReplyAction="http://tempuri.org/IHR/GetEmpContractInfoResponse")]
        System.Data.DataSet GetEmpContractInfo(string empnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpContractInfo", ReplyAction="http://tempuri.org/IHR/GetEmpContractInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpContractInfoAsync(string empnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpIdwithAD", ReplyAction="http://tempuri.org/IHR/GetEmpIdwithADResponse")]
        string GetEmpIdwithAD(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpIdwithAD", ReplyAction="http://tempuri.org/IHR/GetEmpIdwithADResponse")]
        System.Threading.Tasks.Task<string> GetEmpIdwithADAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertList", ReplyAction="http://tempuri.org/IHR/GetCertListResponse")]
        System.Data.DataSet GetCertList(string Category, string Lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertList", ReplyAction="http://tempuri.org/IHR/GetCertListResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCertListAsync(string Category, string Lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetReportTofromEmpID", ReplyAction="http://tempuri.org/IHR/GetReportTofromEmpIDResponse")]
        System.Data.DataSet GetReportTofromEmpID(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetReportTofromEmpID", ReplyAction="http://tempuri.org/IHR/GetReportTofromEmpIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetReportTofromEmpIDAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeIqamainfo", ReplyAction="http://tempuri.org/IHR/GetEmployeeIqamainfoResponse")]
        System.Data.DataSet GetEmployeeIqamainfo(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeIqamainfo", ReplyAction="http://tempuri.org/IHR/GetEmployeeIqamainfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeIqamainfoAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeePassportinfo", ReplyAction="http://tempuri.org/IHR/GetEmployeePassportinfoResponse")]
        System.Data.DataSet GetEmployeePassportinfo(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeePassportinfo", ReplyAction="http://tempuri.org/IHR/GetEmployeePassportinfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeePassportinfoAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetSaudiNumberinfo", ReplyAction="http://tempuri.org/IHR/GetSaudiNumberinfoResponse")]
        System.Data.DataSet GetSaudiNumberinfo(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetSaudiNumberinfo", ReplyAction="http://tempuri.org/IHR/GetSaudiNumberinfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSaudiNumberinfoAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeDescription", ReplyAction="http://tempuri.org/IHR/GetEmployeeDescriptionResponse")]
        System.Data.DataSet GetEmployeeDescription(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeDescription", ReplyAction="http://tempuri.org/IHR/GetEmployeeDescriptionResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeDescriptionAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpSaudiCouncil", ReplyAction="http://tempuri.org/IHR/GetEmpSaudiCouncilResponse")]
        System.Data.DataSet GetEmpSaudiCouncil(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpSaudiCouncil", ReplyAction="http://tempuri.org/IHR/GetEmpSaudiCouncilResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpSaudiCouncilAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpHeadDept", ReplyAction="http://tempuri.org/IHR/GetEmpHeadDeptResponse")]
        System.Data.DataSet GetEmpHeadDept(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpHeadDept", ReplyAction="http://tempuri.org/IHR/GetEmpHeadDeptResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpHeadDeptAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetIqamaSaudiPassportNo", ReplyAction="http://tempuri.org/IHR/GetIqamaSaudiPassportNoResponse")]
        System.Data.DataSet GetIqamaSaudiPassportNo(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetIqamaSaudiPassportNo", ReplyAction="http://tempuri.org/IHR/GetIqamaSaudiPassportNoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetIqamaSaudiPassportNoAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpDependant", ReplyAction="http://tempuri.org/IHR/GetEmpDependantResponse")]
        System.Data.DataSet GetEmpDependant(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpDependant", ReplyAction="http://tempuri.org/IHR/GetEmpDependantResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpDependantAsync(string empNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeLangInfo", ReplyAction="http://tempuri.org/IHR/GetEmployeeLangInfoResponse")]
        System.Data.DataSet GetEmployeeLangInfo(string empNo, string Lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeLangInfo", ReplyAction="http://tempuri.org/IHR/GetEmployeeLangInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeLangInfoAsync(string empNo, string Lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertificateRefno", ReplyAction="http://tempuri.org/IHR/GetCertificateRefnoResponse")]
        System.Data.DataSet GetCertificateRefno(string empnum, string refno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertificateRefno", ReplyAction="http://tempuri.org/IHR/GetCertificateRefnoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCertificateRefnoAsync(string empnum, string refno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Authentication_ActiveDirectory", ReplyAction="http://tempuri.org/IHR/Authentication_ActiveDirectoryResponse")]
        string Authentication_ActiveDirectory(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Authentication_ActiveDirectory", ReplyAction="http://tempuri.org/IHR/Authentication_ActiveDirectoryResponse")]
        System.Threading.Tasks.Task<string> Authentication_ActiveDirectoryAsync(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertPurpose", ReplyAction="http://tempuri.org/IHR/GetCertPurposeResponse")]
        System.Data.DataSet GetCertPurpose(string Lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertPurpose", ReplyAction="http://tempuri.org/IHR/GetCertPurposeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCertPurposeAsync(string Lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertType", ReplyAction="http://tempuri.org/IHR/GetCertTypeResponse")]
        System.Data.DataSet GetCertType(string Lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetCertType", ReplyAction="http://tempuri.org/IHR/GetCertTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCertTypeAsync(string Lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/InsertVactionRequest", ReplyAction="http://tempuri.org/IHR/InsertVactionRequestResponse")]
        int InsertVactionRequest(string P_STAFF_ID, int P_VACATION_TYPE_ID, System.DateTime P_START_DATE, int P_VACATION_DAY, System.DateTime P_END_DATE, string P_PAYROLL_TYPE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/InsertVactionRequest", ReplyAction="http://tempuri.org/IHR/InsertVactionRequestResponse")]
        System.Threading.Tasks.Task<int> InsertVactionRequestAsync(string P_STAFF_ID, int P_VACATION_TYPE_ID, System.DateTime P_START_DATE, int P_VACATION_DAY, System.DateTime P_END_DATE, string P_PAYROLL_TYPE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/ReturnLeaveRequest", ReplyAction="http://tempuri.org/IHR/ReturnLeaveRequestResponse")]
        bool ReturnLeaveRequest(string P_STAFF_ID, int P_VACATION_TYPE_ID, System.DateTime p_Work_start_date, string p_Document_AcceptedYN, string p_ExtraDays_AcceptedYN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/ReturnLeaveRequest", ReplyAction="http://tempuri.org/IHR/ReturnLeaveRequestResponse")]
        System.Threading.Tasks.Task<bool> ReturnLeaveRequestAsync(string P_STAFF_ID, int P_VACATION_TYPE_ID, System.DateTime p_Work_start_date, string p_Document_AcceptedYN, string p_ExtraDays_AcceptedYN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/DeleteLeaveRequest", ReplyAction="http://tempuri.org/IHR/DeleteLeaveRequestResponse")]
        bool DeleteLeaveRequest(int P_VACATION_TYPE_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/DeleteLeaveRequest", ReplyAction="http://tempuri.org/IHR/DeleteLeaveRequestResponse")]
        System.Threading.Tasks.Task<bool> DeleteLeaveRequestAsync(int P_VACATION_TYPE_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpLeaves", ReplyAction="http://tempuri.org/IHR/GetEmpLeavesResponse")]
        System.Data.DataSet GetEmpLeaves(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpLeaves", ReplyAction="http://tempuri.org/IHR/GetEmpLeavesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpLeavesAsync(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeInfoRMH", ReplyAction="http://tempuri.org/IHR/GetEmployeeInfoRMHResponse")]
        System.Data.DataSet GetEmployeeInfoRMH(string empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeInfoRMH", ReplyAction="http://tempuri.org/IHR/GetEmployeeInfoRMHResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeInfoRMHAsync(string empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeePointofHire", ReplyAction="http://tempuri.org/IHR/GetEmployeePointofHireResponse")]
        string GetEmployeePointofHire(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeePointofHire", ReplyAction="http://tempuri.org/IHR/GetEmployeePointofHireResponse")]
        System.Threading.Tasks.Task<string> GetEmployeePointofHireAsync(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/InsertCertificate", ReplyAction="http://tempuri.org/IHR/InsertCertificateResponse")]
        int InsertCertificate(string Staff_id, int cert_type, int Reason, System.DateTime CertDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/InsertCertificate", ReplyAction="http://tempuri.org/IHR/InsertCertificateResponse")]
        System.Threading.Tasks.Task<int> InsertCertificateAsync(string Staff_id, int cert_type, int Reason, System.DateTime CertDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeDeptCode", ReplyAction="http://tempuri.org/IHR/GetEmployeeDeptCodeResponse")]
        System.Data.DataSet GetEmployeeDeptCode(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployeeDeptCode", ReplyAction="http://tempuri.org/IHR/GetEmployeeDeptCodeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeDeptCodeAsync(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpLeaveRequestDays", ReplyAction="http://tempuri.org/IHR/GetEmpLeaveRequestDaysResponse")]
        int GetEmpLeaveRequestDays(string _date, string _staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpLeaveRequestDays", ReplyAction="http://tempuri.org/IHR/GetEmpLeaveRequestDaysResponse")]
        System.Threading.Tasks.Task<int> GetEmpLeaveRequestDaysAsync(string _date, string _staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetallDeptList", ReplyAction="http://tempuri.org/IHR/GetallDeptListResponse")]
        System.Data.DataSet GetallDeptList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetallDeptList", ReplyAction="http://tempuri.org/IHR/GetallDeptListResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetallDeptListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpVacations", ReplyAction="http://tempuri.org/IHR/GetEmpVacationsResponse")]
        System.Data.DataSet GetEmpVacations(string _staffID, string f_date, string t_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmpVacations", ReplyAction="http://tempuri.org/IHR/GetEmpVacationsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpVacationsAsync(string _staffID, string f_date, string t_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetVacationDate", ReplyAction="http://tempuri.org/IHR/GetVacationDateResponse")]
        System.Data.DataSet GetVacationDate(string _date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetVacationDate", ReplyAction="http://tempuri.org/IHR/GetVacationDateResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetVacationDateAsync(string _date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHRChannel : Performance.Management.BLL.HRService.IHR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRClient : System.ServiceModel.ClientBase<Performance.Management.BLL.HRService.IHR>, Performance.Management.BLL.HRService.IHR {
        
        public HRClient() {
        }
        
        public HRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetEmployeeInfo(string StaffID) {
            return base.Channel.GetEmployeeInfo(StaffID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeInfoAsync(string StaffID) {
            return base.Channel.GetEmployeeInfoAsync(StaffID);
        }
        
        public System.Data.DataSet GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public System.Data.DataSet GetAllEmployeesDept(string deptcode) {
            return base.Channel.GetAllEmployeesDept(deptcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllEmployeesDeptAsync(string deptcode) {
            return base.Channel.GetAllEmployeesDeptAsync(deptcode);
        }
        
        public System.Data.DataSet GetDept(string deptname) {
            return base.Channel.GetDept(deptname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDeptAsync(string deptname) {
            return base.Channel.GetDeptAsync(deptname);
        }
        
        public System.Data.DataSet GetAllAuthorities() {
            return base.Channel.GetAllAuthorities();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllAuthoritiesAsync() {
            return base.Channel.GetAllAuthoritiesAsync();
        }
        
        public System.Data.DataSet GetAllCompany(string compcode) {
            return base.Channel.GetAllCompany(compcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllCompanyAsync(string compcode) {
            return base.Channel.GetAllCompanyAsync(compcode);
        }
        
        public System.Data.DataSet GetAllCities() {
            return base.Channel.GetAllCities();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllCitiesAsync() {
            return base.Channel.GetAllCitiesAsync();
        }
        
        public System.Data.DataSet GetAllCitiescode(string citycode) {
            return base.Channel.GetAllCitiescode(citycode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllCitiescodeAsync(string citycode) {
            return base.Channel.GetAllCitiescodeAsync(citycode);
        }
        
        public System.Data.DataSet Getallporter() {
            return base.Channel.Getallporter();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetallporterAsync() {
            return base.Channel.GetallporterAsync();
        }
        
        public System.Data.DataSet Getallporterdept(string pcode) {
            return base.Channel.Getallporterdept(pcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetallporterdeptAsync(string pcode) {
            return base.Channel.GetallporterdeptAsync(pcode);
        }
        
        public System.Data.DataSet Getallporterempno(string pemp) {
            return base.Channel.Getallporterempno(pemp);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetallporterempnoAsync(string pemp) {
            return base.Channel.GetallporterempnoAsync(pemp);
        }
        
        public System.Data.DataSet Getsalaryemp(string semp) {
            return base.Channel.Getsalaryemp(semp);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetsalaryempAsync(string semp) {
            return base.Channel.GetsalaryempAsync(semp);
        }
        
        public int GetEmployeeVactionDays(string _date, string _staffID) {
            return base.Channel.GetEmployeeVactionDays(_date, _staffID);
        }
        
        public System.Threading.Tasks.Task<int> GetEmployeeVactionDaysAsync(string _date, string _staffID) {
            return base.Channel.GetEmployeeVactionDaysAsync(_date, _staffID);
        }
        
        public string GetEmployeeGrade(string _staffID) {
            return base.Channel.GetEmployeeGrade(_staffID);
        }
        
        public System.Threading.Tasks.Task<string> GetEmployeeGradeAsync(string _staffID) {
            return base.Channel.GetEmployeeGradeAsync(_staffID);
        }
        
        public int GetCertificateEmp(string _staffID) {
            return base.Channel.GetCertificateEmp(_staffID);
        }
        
        public System.Threading.Tasks.Task<int> GetCertificateEmpAsync(string _staffID) {
            return base.Channel.GetCertificateEmpAsync(_staffID);
        }
        
        public System.Data.DataSet GetSalaryFor(string mthyr, string empnum) {
            return base.Channel.GetSalaryFor(mthyr, empnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSalaryForAsync(string mthyr, string empnum) {
            return base.Channel.GetSalaryForAsync(mthyr, empnum);
        }
        
        public string GetSeqNo(string mthyr) {
            return base.Channel.GetSeqNo(mthyr);
        }
        
        public System.Threading.Tasks.Task<string> GetSeqNoAsync(string mthyr) {
            return base.Channel.GetSeqNoAsync(mthyr);
        }
        
        public System.Data.DataSet GetEmpLastVaction(string empnum) {
            return base.Channel.GetEmpLastVaction(empnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpLastVactionAsync(string empnum) {
            return base.Channel.GetEmpLastVactionAsync(empnum);
        }
        
        public System.Data.DataSet GetEmpContractInfo(string empnum) {
            return base.Channel.GetEmpContractInfo(empnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpContractInfoAsync(string empnum) {
            return base.Channel.GetEmpContractInfoAsync(empnum);
        }
        
        public string GetEmpIdwithAD(string Username) {
            return base.Channel.GetEmpIdwithAD(Username);
        }
        
        public System.Threading.Tasks.Task<string> GetEmpIdwithADAsync(string Username) {
            return base.Channel.GetEmpIdwithADAsync(Username);
        }
        
        public System.Data.DataSet GetCertList(string Category, string Lang) {
            return base.Channel.GetCertList(Category, Lang);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCertListAsync(string Category, string Lang) {
            return base.Channel.GetCertListAsync(Category, Lang);
        }
        
        public System.Data.DataSet GetReportTofromEmpID(string empNo) {
            return base.Channel.GetReportTofromEmpID(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetReportTofromEmpIDAsync(string empNo) {
            return base.Channel.GetReportTofromEmpIDAsync(empNo);
        }
        
        public System.Data.DataSet GetEmployeeIqamainfo(string empNo) {
            return base.Channel.GetEmployeeIqamainfo(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeIqamainfoAsync(string empNo) {
            return base.Channel.GetEmployeeIqamainfoAsync(empNo);
        }
        
        public System.Data.DataSet GetEmployeePassportinfo(string empNo) {
            return base.Channel.GetEmployeePassportinfo(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeePassportinfoAsync(string empNo) {
            return base.Channel.GetEmployeePassportinfoAsync(empNo);
        }
        
        public System.Data.DataSet GetSaudiNumberinfo(string empNo) {
            return base.Channel.GetSaudiNumberinfo(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSaudiNumberinfoAsync(string empNo) {
            return base.Channel.GetSaudiNumberinfoAsync(empNo);
        }
        
        public System.Data.DataSet GetEmployeeDescription(string empNo) {
            return base.Channel.GetEmployeeDescription(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeDescriptionAsync(string empNo) {
            return base.Channel.GetEmployeeDescriptionAsync(empNo);
        }
        
        public System.Data.DataSet GetEmpSaudiCouncil(string empNo) {
            return base.Channel.GetEmpSaudiCouncil(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpSaudiCouncilAsync(string empNo) {
            return base.Channel.GetEmpSaudiCouncilAsync(empNo);
        }
        
        public System.Data.DataSet GetEmpHeadDept(string empNo) {
            return base.Channel.GetEmpHeadDept(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpHeadDeptAsync(string empNo) {
            return base.Channel.GetEmpHeadDeptAsync(empNo);
        }
        
        public System.Data.DataSet GetIqamaSaudiPassportNo(string empNo) {
            return base.Channel.GetIqamaSaudiPassportNo(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetIqamaSaudiPassportNoAsync(string empNo) {
            return base.Channel.GetIqamaSaudiPassportNoAsync(empNo);
        }
        
        public System.Data.DataSet GetEmpDependant(string empNo) {
            return base.Channel.GetEmpDependant(empNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpDependantAsync(string empNo) {
            return base.Channel.GetEmpDependantAsync(empNo);
        }
        
        public System.Data.DataSet GetEmployeeLangInfo(string empNo, string Lang) {
            return base.Channel.GetEmployeeLangInfo(empNo, Lang);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeLangInfoAsync(string empNo, string Lang) {
            return base.Channel.GetEmployeeLangInfoAsync(empNo, Lang);
        }
        
        public System.Data.DataSet GetCertificateRefno(string empnum, string refno) {
            return base.Channel.GetCertificateRefno(empnum, refno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCertificateRefnoAsync(string empnum, string refno) {
            return base.Channel.GetCertificateRefnoAsync(empnum, refno);
        }
        
        public string Authentication_ActiveDirectory(string userid, string password) {
            return base.Channel.Authentication_ActiveDirectory(userid, password);
        }
        
        public System.Threading.Tasks.Task<string> Authentication_ActiveDirectoryAsync(string userid, string password) {
            return base.Channel.Authentication_ActiveDirectoryAsync(userid, password);
        }
        
        public System.Data.DataSet GetCertPurpose(string Lang) {
            return base.Channel.GetCertPurpose(Lang);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCertPurposeAsync(string Lang) {
            return base.Channel.GetCertPurposeAsync(Lang);
        }
        
        public System.Data.DataSet GetCertType(string Lang) {
            return base.Channel.GetCertType(Lang);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCertTypeAsync(string Lang) {
            return base.Channel.GetCertTypeAsync(Lang);
        }
        
        public int InsertVactionRequest(string P_STAFF_ID, int P_VACATION_TYPE_ID, System.DateTime P_START_DATE, int P_VACATION_DAY, System.DateTime P_END_DATE, string P_PAYROLL_TYPE) {
            return base.Channel.InsertVactionRequest(P_STAFF_ID, P_VACATION_TYPE_ID, P_START_DATE, P_VACATION_DAY, P_END_DATE, P_PAYROLL_TYPE);
        }
        
        public System.Threading.Tasks.Task<int> InsertVactionRequestAsync(string P_STAFF_ID, int P_VACATION_TYPE_ID, System.DateTime P_START_DATE, int P_VACATION_DAY, System.DateTime P_END_DATE, string P_PAYROLL_TYPE) {
            return base.Channel.InsertVactionRequestAsync(P_STAFF_ID, P_VACATION_TYPE_ID, P_START_DATE, P_VACATION_DAY, P_END_DATE, P_PAYROLL_TYPE);
        }
        
        public bool ReturnLeaveRequest(string P_STAFF_ID, int P_VACATION_TYPE_ID, System.DateTime p_Work_start_date, string p_Document_AcceptedYN, string p_ExtraDays_AcceptedYN) {
            return base.Channel.ReturnLeaveRequest(P_STAFF_ID, P_VACATION_TYPE_ID, p_Work_start_date, p_Document_AcceptedYN, p_ExtraDays_AcceptedYN);
        }
        
        public System.Threading.Tasks.Task<bool> ReturnLeaveRequestAsync(string P_STAFF_ID, int P_VACATION_TYPE_ID, System.DateTime p_Work_start_date, string p_Document_AcceptedYN, string p_ExtraDays_AcceptedYN) {
            return base.Channel.ReturnLeaveRequestAsync(P_STAFF_ID, P_VACATION_TYPE_ID, p_Work_start_date, p_Document_AcceptedYN, p_ExtraDays_AcceptedYN);
        }
        
        public bool DeleteLeaveRequest(int P_VACATION_TYPE_ID) {
            return base.Channel.DeleteLeaveRequest(P_VACATION_TYPE_ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteLeaveRequestAsync(int P_VACATION_TYPE_ID) {
            return base.Channel.DeleteLeaveRequestAsync(P_VACATION_TYPE_ID);
        }
        
        public System.Data.DataSet GetEmpLeaves(string StaffID) {
            return base.Channel.GetEmpLeaves(StaffID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpLeavesAsync(string StaffID) {
            return base.Channel.GetEmpLeavesAsync(StaffID);
        }
        
        public System.Data.DataSet GetEmployeeInfoRMH(string empid) {
            return base.Channel.GetEmployeeInfoRMH(empid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeInfoRMHAsync(string empid) {
            return base.Channel.GetEmployeeInfoRMHAsync(empid);
        }
        
        public string GetEmployeePointofHire(string StaffID) {
            return base.Channel.GetEmployeePointofHire(StaffID);
        }
        
        public System.Threading.Tasks.Task<string> GetEmployeePointofHireAsync(string StaffID) {
            return base.Channel.GetEmployeePointofHireAsync(StaffID);
        }
        
        public int InsertCertificate(string Staff_id, int cert_type, int Reason, System.DateTime CertDate) {
            return base.Channel.InsertCertificate(Staff_id, cert_type, Reason, CertDate);
        }
        
        public System.Threading.Tasks.Task<int> InsertCertificateAsync(string Staff_id, int cert_type, int Reason, System.DateTime CertDate) {
            return base.Channel.InsertCertificateAsync(Staff_id, cert_type, Reason, CertDate);
        }
        
        public System.Data.DataSet GetEmployeeDeptCode(string StaffID) {
            return base.Channel.GetEmployeeDeptCode(StaffID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeeDeptCodeAsync(string StaffID) {
            return base.Channel.GetEmployeeDeptCodeAsync(StaffID);
        }
        
        public int GetEmpLeaveRequestDays(string _date, string _staffID) {
            return base.Channel.GetEmpLeaveRequestDays(_date, _staffID);
        }
        
        public System.Threading.Tasks.Task<int> GetEmpLeaveRequestDaysAsync(string _date, string _staffID) {
            return base.Channel.GetEmpLeaveRequestDaysAsync(_date, _staffID);
        }
        
        public System.Data.DataSet GetallDeptList() {
            return base.Channel.GetallDeptList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetallDeptListAsync() {
            return base.Channel.GetallDeptListAsync();
        }
        
        public System.Data.DataSet GetEmpVacations(string _staffID, string f_date, string t_date) {
            return base.Channel.GetEmpVacations(_staffID, f_date, t_date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpVacationsAsync(string _staffID, string f_date, string t_date) {
            return base.Channel.GetEmpVacationsAsync(_staffID, f_date, t_date);
        }
        
        public System.Data.DataSet GetVacationDate(string _date) {
            return base.Channel.GetVacationDate(_date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetVacationDateAsync(string _date) {
            return base.Channel.GetVacationDateAsync(_date);
        }
    }
}
